/*
  # Seed Bot Templates with Correct Schema
  
  Creates realistic bot templates for the marketplace.
*/

INSERT INTO bot_templates (
  name, description, strategy_type, risk_level,
  min_investment, expected_return_percent,
  price_monthly, published, featured,
  total_return, win_rate, subscribers_count,
  configuration, backtesting_results,
  created_at
)
VALUES
  (
    'Alpha Momentum Pro',
    'Advanced momentum trading strategy that identifies strong price trends and rides them for maximum profit. Uses multiple timeframe analysis and momentum indicators to capture explosive moves.',
    'momentum',
    'medium',
    10000,
    25.0,
    99.00,
    true,
    true,
    28.5,
    68.0,
    247,
    '{"indicators": ["RSI", "MACD", "Volume"], "timeframes": ["15m", "1h", "4h"], "max_positions": 5}',
    '{"total_trades": 450, "winning_trades": 306, "avg_profit": 2.1, "max_drawdown": 12.0, "sharpe_ratio": 1.8}',
    NOW() - INTERVAL '180 days'
  ),
  (
    'Mean Reversion Master',
    'Capitalizes on price reversions to the mean. Perfect for range-bound markets. Uses statistical analysis to identify overbought and oversold conditions with high accuracy.',
    'mean_reversion',
    'low',
    5000,
    18.0,
    79.00,
    true,
    true,
    22.3,
    72.0,
    412,
    '{"bollinger_bands": true, "rsi_threshold": 30, "mean_period": 20, "max_positions": 3}',
    '{"total_trades": 680, "winning_trades": 490, "avg_profit": 1.5, "max_drawdown": 8.0, "sharpe_ratio": 1.5}',
    NOW() - INTERVAL '240 days'
  ),
  (
    'Trend Following Elite',
    'Long-term trend following system that captures major market moves. Ideal for patient traders looking for consistent returns with minimal drawdowns.',
    'trend_following',
    'low',
    15000,
    20.0,
    129.00,
    true,
    true,
    24.7,
    65.0,
    189,
    '{"moving_averages": [50, 200], "atr_multiplier": 2.0, "trailing_stop": true, "max_positions": 4}',
    '{"total_trades": 320, "winning_trades": 208, "avg_profit": 3.2, "max_drawdown": 10.0, "sharpe_ratio": 1.6}',
    NOW() - INTERVAL '300 days'
  ),
  (
    'Scalper AI Ultra',
    'High-frequency scalping bot for aggressive traders. Makes multiple quick trades to capture small price movements. Advanced algorithms with sub-second execution.',
    'scalping',
    'high',
    25000,
    35.0,
    149.00,
    true,
    false,
    38.2,
    62.0,
    93,
    '{"tick_size": 0.01, "profit_target": 0.5, "stop_loss": 0.3, "max_positions": 10, "order_type": "limit"}',
    '{"total_trades": 2400, "winning_trades": 1488, "avg_profit": 0.8, "max_drawdown": 18.0, "sharpe_ratio": 2.1}',
    NOW() - INTERVAL '120 days'
  ),
  (
    'Volatility Harvester',
    'Profits from market volatility using advanced volatility indicators and dynamic position sizing. Built-in risk management adapts to market conditions.',
    'volatility',
    'medium',
    20000,
    29.0,
    119.00,
    true,
    true,
    31.4,
    66.0,
    156,
    '{"vix_threshold": 20, "iv_percentile": 75, "position_scaling": true, "hedging": true}',
    '{"total_trades": 520, "winning_trades": 343, "avg_profit": 2.5, "max_drawdown": 15.0, "sharpe_ratio": 1.9}',
    NOW() - INTERVAL '200 days'
  ),
  (
    'Conservative Growth',
    'Low-risk strategy focused on capital preservation and steady growth. Perfect for beginners and risk-averse traders seeking consistent returns.',
    'conservative',
    'low',
    5000,
    13.0,
    59.00,
    true,
    false,
    15.2,
    75.0,
    523,
    '{"risk_per_trade": 0.5, "diversification": true, "blue_chip_only": true, "max_positions": 8}',
    '{"total_trades": 180, "winning_trades": 135, "avg_profit": 1.8, "max_drawdown": 5.0, "sharpe_ratio": 1.4}',
    NOW() - INTERVAL '360 days'
  ),
  (
    'Breakout Hunter',
    'Identifies and trades breakouts from consolidation patterns. High win rate with controlled risk using volume confirmation and pattern recognition.',
    'breakout',
    'medium',
    12000,
    27.0,
    109.00,
    true,
    false,
    29.8,
    70.0,
    201,
    '{"volume_multiplier": 1.5, "consolidation_period": 10, "breakout_threshold": 2.0, "max_positions": 5}',
    '{"total_trades": 380, "winning_trades": 266, "avg_profit": 2.8, "max_drawdown": 13.0, "sharpe_ratio": 1.7}',
    NOW() - INTERVAL '150 days'
  ),
  (
    'Arbitrage Seeker',
    'Exploits price differences across markets and exchanges. Low risk, consistent returns. Statistical arbitrage with automated execution.',
    'arbitrage',
    'low',
    30000,
    15.0,
    199.00,
    true,
    false,
    17.5,
    80.0,
    67,
    '{"exchanges": ["NYSE", "NASDAQ", "LSE"], "price_threshold": 0.5, "execution_speed": "instant", "max_positions": 15}',
    '{"total_trades": 1200, "winning_trades": 960, "avg_profit": 0.6, "max_drawdown": 6.0, "sharpe_ratio": 2.0}',
    NOW() - INTERVAL '270 days'
  )
ON CONFLICT DO NOTHING;
